### ISSUE TITLE
Sugestão p/ exemplo dos pontos flutuantes!

### ISSUE THREAD

**Issue by ftonato** [andersonFaro9/workshop-swift-free#1]
Tenho uma sugestão para o exemplo dos [Flutuantes](https://github.com/andersonFaro9/workshop-swift-free#flutuantes)

``` swift
//Float
var x: Float = 300.0123456
print(x) // 300.012

//Double
var y: Double = 300.0123456
print(y) // 300.0123456
```

**Comment by andersonFaro9** [comment]
Aceito, com certeza, manda bala!

**Comment by andersonFaro9** [comment]
Cara, tem pouco tempo que uso github... sobre essa alteração, lá no seu "fork" está como deveria ficar mas no meu, está diferente, algo que faltou eu fazer?

**Comment by andersonFaro9** [comment]
Tudo certo, eu que viajei no cometa! hehehe

**Comment by ftonato** [comment]
Na verdade está diferente, por que tu ainda não aceitou o _Pull Request_!
Ele não tinha conflitos quando enviei, mas agora que você alterou o README.md ele gerou conflitos, você precisa resolver eles antes de aceitar o _Pull Request_, mas se já conseguiu entender o problema, basta aceitar e corrigir :+1:

**Comment by ftonato** [comment]
Ah, e só para lembrar: Quando você aceitar o _pull request_ essa issue irá fechar automaticamente :)

**Comment by andersonFaro9** [comment]
Como faço pra aceitar o pull request?

**Comment by ftonato** [comment]
Assiste após os 5 minutos https://www.youtube.com/watch?v=FQsBmnZvBdc

**Comment by andersonFaro9** [comment]
Pera.

**Comment by andersonFaro9** [comment]
Man, aqui tá foda! tentei fazer pela linha de comando e não consegui... tem tempo que não estudo o git e confesso que esse esquema de "pull request" me pegou de surpresa!

Poderíamos fazer o seguinte:
Modifique aquela parte por favor e assim ficamos quites, pode ser?

**Comment by ftonato** [comment]
Quando puder, assista e talvez você entenda um pouco melhor sobre!
https://www.youtube.com/watch?v=TReVFOxhh7E

**Comment by ftonato** [comment]
Não entendi de fato o que você me pediu, mas você pode recusar meu **pull request** e pegar a parte de código que escrevi lá e substituir manualmente no seu arquivo README.md :)
Logo depois você fecha essa **issue** :+1:

**Comment by ftonato** [comment]
Agora que percebi que já arrumou ;)
Cancela o **pull request** que eu fecho a issue!

**Comment by andersonFaro9** [comment]
Imaginei que isso pudesse impactar na sua reputação já que você fez a alteração e eu confesso preciso aprender mais sobre o git e o github... cara fizeram outros forks mas eu até agora não encontrei onde faço para aceitar o pull request...

**Comment by ftonato** [comment]
Cara, sem problemas, as pessoas recusam pull request, isso é normal!
Agora, não é por que as pessoas fizeram fork que elas farão pull request...
No primeiro vídeo que te mandei o link aparece claramente ele fazendo um fork, enviando um pull request e aceitando um pull request!

**Comment by andersonFaro9** [comment]
Blza!
